import{ANATOMY,DEVICES,FLOW,PHYS}from'../config/anatomy';
export function stenosisProfile(s:number){const a=ANATOMY.lad.lesionStart,l=ANATOMY.lad.lesionLength;if(s<=a||s>=a+l)return 0;const x=(s-a)/l,e=.36;if(x<e)return .9*.5*(1-Math.cos(Math.PI*x/e));if(x>1-e)return .9*.5*(1-Math.cos(Math.PI*(1-x)/e));return .9}
export function pressureDiameter(k:'balloon'|'stent',n:number,p:number){const d=k==='balloon'?DEVICES.balloon:DEVICES.stent;if(p<=0)return n*.32;if(p<2)return n*(.32+.34*p);return n*(1+d.compliance*(p-d.nominal))}
export function coverageMargins(c:number,l:number):[number,number]{const a=ANATOMY.lad.lesionStart,b=a+ANATOMY.lad.lesionLength;return[a-(c-l/2),(c+l/2)-b]}
export function flowFactor(ds:number){if(ds<.6)return 1;if(ds>=.98)return 0;const x=(ds-.6)/.38;return Math.max(0,1-.78*x**1.8)}
export function timi(f:number):0|1|2|3{return f>=FLOW.timi3?3:f>=FLOW.timi2?2:f>FLOW.timi1?1:0}
export function physiology(prev:{ischaemia:number;occlusion:number},dt:number,flow:number,heparin:boolean){const poor=flow<.25,target=poor?1:Math.max(0,1-flow),tau=target>prev.ischaemia?PHYS.riseTau:PHYS.recoveryTau,ischaemia=prev.ischaemia+(target-prev.ischaemia)*(1-Math.exp(-dt/tau)),occlusion=poor?prev.occlusion+dt:0;return{ischaemia,occlusion,st:ischaemia*PHYS.maxST,hr:Math.round(PHYS.hr+ischaemia*25),sbp:Math.round(PHYS.sbp-Math.max(0,occlusion-40)*1.2),act:heparin?PHYS.heparinAct:PHYS.act,unstable:occlusion>PHYS.unstableSec}}
export interface Summary{complete:boolean;residual:number;timi:number;ratio:number;margins:[number,number];heparin:boolean;predilate:boolean;qca:boolean;dissection:boolean;sealed:boolean;rupture:boolean;forcing:number;inflation:number;contrast:number;fluoro:number;views:number}
export function buildDebrief(s:Summary){let score=100;const items:{name:string;value:string;ok:boolean;tip:string}[]=[];const add=(name:string,value:string,ok:boolean,penalty:number,tip:string)=>{if(!ok)score-=penalty;items.push({name,value,ok,tip})};add('Residual stenosis',`${Math.round(s.residual*100)}%`,s.residual<=.1,12,'Aim for ≤10%.');add('Final flow',`TIMI ${s.timi}`,s.timi===3,15,'TIMI 3 is the target.');add('Stent size',`${s.ratio.toFixed(2)}×`,s.ratio>=.95&&s.ratio<=1.15,12,'Match the reference vessel.');add('Coverage',`${s.margins[0].toFixed(1)} / ${s.margins[1].toFixed(1)} mm`,Math.min(...s.margins)>=1.5,14,'Cover both lesion edges.');add('Heparin',s.heparin?'Given':'Missed',s.heparin,12,'Anticoagulate before wiring.');add('Pre-dilation',s.predilate?'Done':'Missed',s.predilate,5,'Prepare severe lesions.');add('QCA',s.qca?'Used':'Not used',s.qca,5,'Measure before sizing.');add('Dissection',s.dissection?(s.sealed?'Sealed':'Unsealed'):'None',!s.dissection||s.sealed,16,'Seal flow-limiting injury.');add('Rupture',s.rupture?'Yes':'No',!s.rupture,10,'Respect rated burst pressure.');add('Wire forcing',String(s.forcing),s.forcing===0,6,'Advance gently.');add('Longest inflation',`${s.inflation.toFixed(0)} s`,s.inflation<=30,6,'Limit occlusion time.');add('Final views',String(s.views),s.views>=2,8,'Use two projections.');if(!s.complete)score=Math.min(45,score);score=Math.max(0,Math.round(score));return{score,grade:!s.complete?'Incomplete':score>=90?'Excellent':score>=75?'Good':score>=60?'Acceptable':'Needs work',items}}
